default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  host: localhost
  database: exsilio_development
production:
  <<: *default
  database: exsilio_production
  username: exsilio
  password: <%= ENV["EXSILIO_DATABASE_PASSWORD"] %>
